name: Scrape latest JSON API data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest formula data
      run: |-
        curl https://formulae.brew.sh/api/formula.json | jq . > formula.json
    - name: Fetch latest cask data
      run: |-
        curl https://formulae.brew.sh/api/cask.json | jq . > cask.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest JSON API data: ${timestamp}" || exit 0
        git push
