name: Run all code quality tools

on:
  push:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: '0.33.0'
      - name: Install dependencies
        run: rye sync --no-lock
      - name: Format check
        run: rye fmt --check
      - name: Type check
        run: rye run mypy --strict src
