name: Run all code quality tools

on:
  push:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Configure Python with cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --only=dev
      - run: poetry run ruff check .
      - run: poetry run mypy --strict .
