name: Generate RSS feeds for all tracked API sources

on:
  schedule:
  - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: '0.33.0'
      - name: Install dependencies
        run: rye sync --no-lock
      - uses: jorgebg/stateful-action@v0.1
      - name: Generate RSS feed based on DB
        run: rye run generate-rss formula .state/feed.db .state/formula.rss 20240501
