name: Upsert SQLite DB with JSON API updates

on:
  schedule:
  - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: '0.33.0'
      - name: Install dependencies
        run: rye sync --no-lock
      - uses: jorgebg/stateful-action@v0.1
      - name: Upsert data from Formula JSON API
        run: rye run ingest-json-api formula .state/feed.db 'https://formulae.brew.sh/api/formula.json'
