name: Capture, update and post latest formula

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 12 * * *'

jobs:
  capture-update-post:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v2
      with:
        version: "0.5.0"
        enable-cache: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch latest formula data
      run: |-
        uv run homebrew-new-bot api formula
    - name: Update package database
      run: |-
        uv run homebrew-new-bot database update formula
    - name: Post new formula
      run: |-
        uv run homebrew-new-bot toot --max_toots_per_execution=${{ vars.MAX_TOOTS_PER_EXECUTION }} --mastodon_api_base_url=${{ vars.MASTODON_API_BASE_URL }} --mastodon_access_token=${{ secrets.MASTODON_ACCESS_TOKEN }}  --mastodon_client_secret=${{ secrets.MASTODON_CLIENT_SECRET }} formula
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest state: ${timestamp}" || exit 0
        git push
