name: Post new formula and casks

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */2 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install poetry
      run: pipx install poetry
    - name: Configure Python with cache
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Add venv bin to PATH
      run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
    - name: Configure toot CLI
      env:
        TOOT_CONFIG: ${{ secrets.TOOT_CONFIG }}
      run: |-
        mkdir -p ~/.config/toot
        echo $TOOT_CONFIG > ~/.config/toot/config.json
    - name: Run bot script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        MAX_TOOTS_PER_EXECUTION: ${{ vars.MAX_TOOTS_PER_EXECUTION }}
      run: poetry run python3 post.py
    - name: Commit changes to state directory
      uses: EndBug/add-and-commit@v9
      with:
        add: 'state'
        message: 'Updated state from last workflow run'